wandb_version: 1

batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.14.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681680507.850154
    t:
      1:
      - 2
      - 3
      - 53
      - 55
      2:
      - 2
      - 3
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      - 37
      4: 3.10.8
      5: 0.14.2
      8:
      - 3
      - 5
      - 9
